SELECT E1.EMPLOYEE_ID , NAME , E2.REPORTS_COUNT , E2.AVERAGE_AGE
FROM EMPLOYEES E1
INNER JOIN( 
SELECT REPORTS_TO AS EMPLOYEE_ID, COUNT(NAME) AS REPORTS_COUNT , ROUND(AVG(AGE) , 0) AS AVERAGE_AGE 
FROM EMPLOYEES 
GROUP BY REPORTS_TO
HAVING REPORTS_COUNT >= 1
) E2 ON E1.EMPLOYEE_ID = E2.EMPLOYEE_ID
ORDER BY E1.EMPLOYEE_ID