SELECT DISTINCT * FROM
(SELECT EMPLOYEE_ID , DEPARTMENT_ID
FROM EMPLOYEE
GROUP BY EMPLOYEE_ID
HAVING COUNT(DEPARTMENT_ID) = 1
UNION ALL
SELECT EMPLOYEE_ID , DEPARTMENT_ID
FROM EMPLOYEE
WHERE PRIMARY_FLAG = 'Y'
) C