WITH CTE AS(
  SELECT PERSON_NAME,
  SUM(WEIGHT) OVER(ORDER BY TURN ASC) AS TTL_WEIGHT
  FROM QUEUE)
SELECT PERSON_NAME
FROM CTE
WHERE TTL_WEIGHT = (SELECT MAX(TTL_WEIGHT) FROM CTE WHERE TTL_WEIGHT <= 1000)