SELECT DISTINCT P1.PRODUCT_ID , 
CASE WHEN P3.NEW_PRICE IS NULL THEN 10 ELSE P3.NEW_PRICE END AS PRICE
FROM PRODUCTS P1
LEFT JOIN 
(SELECT PRODUCT_ID , MAX(CHANGE_DATE) AS CHANGE_DATE
FROM PRODUCTS
WHERE DATEDIFF(CHANGE_DATE , '2019-08-16') <= 0
GROUP BY PRODUCT_ID
) P2 ON P1.PRODUCT_ID = P2.PRODUCT_ID
LEFT JOIN PRODUCTS P3
ON P3.CHANGE_DATE = P2.CHANGE_DATE AND P3.PRODUCT_ID = P1.PRODUCT_ID