SELECT P.PRODUCT_NAME , SUM(UNIT) AS unit
FROM PRODUCTS P
LEFT JOIN ORDERS O
ON P.PRODUCT_ID = O.PRODUCT_ID
WHERE ORDER_DATE >= '2020-02-01' AND ORDER_DATE < '2020-03-01'
GROUP BY P.PRODUCT_ID 
HAVING unit >= 100