SELECT R.CONTEST_ID ,  ROUND(COUNT(U.USER_ID) / (SELECT COUNT(USER_ID) FROM USERS) * 100, 2) AS PERCENTAGE
FROM USERS U
JOIN REGISTER R
ON R.USER_ID = U.USER_ID
GROUP BY R.CONTEST_ID
ORDER BY PERCENTAGE DESC, CONTEST_ID