SELECT  
ROUND(SUM(CASE WHEN D2.CUSTOMER_PREF_DELIVERY_DATE = Z.MIN_ORDER THEN 1 ELSE 0 END) * 100 / COUNT(Z.CUSTOMER_ID) , 2) AS immediate_percentage
FROM DELIVERY D2
RIGHT JOIN(
  SELECT D1.CUSTOMER_ID , MIN(ORDER_DATE) AS MIN_ORDER
  FROM DELIVERY D1
  GROUP BY D1.CUSTOMER_ID) Z
  ON D2.CUSTOMER_ID = Z.CUSTOMER_ID AND D2.ORDER_DATE = Z.MIN_ORDER
