SELECT ROUND(COUNT(DISTINCT A1.PLAYER_ID) / (SELECT COUNT(DISTINCT PLAYER_ID) FROM ACTIVITY) , 2) AS fraction
FROM 
(
  SELECT PLAYER_ID , MIN(EVENT_DATE) AS EVENT_DATE
  FROM ACTIVITY
  GROUP BY PLAYER_ID
) A1
INNER JOIN ACTIVITY A2 ON DATEDIFF(A2.EVENT_DATE , A1.EVENT_DATE) = 1 AND A1.PLAYER_ID = A2.PLAYER_ID 
