SELECT SUBSTR(T.TRANS_DATE , 1 , 7) AS MONTH ,
T.COUNTRY,
COUNT(T.ID) AS TRANS_COUNT,
SUM(CASE WHEN T.STATE = 'approved' THEN 1 ELSE 0 END) AS APPROVED_COUNT,
SUM(T.AMOUNT) AS TRANS_TOTAL_AMOUNT,
SUM(CASE WHEN T.STATE = 'approved' THEN AMOUNT ELSE 0 END) AS APPROVED_TOTAL_AMOUNT
FROM TRANSACTIONS T
GROUP BY MONTH , T.COUNTRY