SELECT A1.MACHINE_ID , ROUND(AVG(A2.TIMESTAMP - A1.TIMESTAMP) , 3) AS processing_time
FROM ACTIVITY A1 , ACTIVITY A2
WHERE A1.MACHINE_ID = A2.MACHINE_ID AND A1.PROCESS_ID = A2.PROCESS_ID AND A1.ACTIVITY_TYPE != A2.ACTIVITY_TYPE AND A1.ACTIVITY_TYPE = 'start'
GROUP BY MACHINE_ID
ORDER BY MACHINE_ID