SELECT  S.STUDENT_ID , S.STUDENT_NAME , SB.SUBJECT_NAME , COUNT(E.STUDENT_ID) AS attended_exams
FROM STUDENTS S
JOIN SUBJECTS SB
LEFT JOIN EXAMINATIONS E ON E.STUDENT_ID = S.STUDENT_ID AND E.SUBJECT_NAME = SB.SUBJECT_NAME
GROUP BY S.STUDENT_ID , SB.SUBJECT_NAME
ORDER BY S.STUDENT_ID , SB.SUBJECT_NAME