SELECT NAME , 
 CASE WHEN SUM(DISTANCE) IS NOT NULL THEN SUM(DISTANCE)
 ELSE 0 END AS travelled_distance
FROM USERS U
LEFT JOIN RIDES R ON U.ID = R.USER_ID
GROUP BY NAME, U.id
ORDER BY travelled_distance DESC , NAME 