SELECT D.NAME AS Department , E.NAME AS Employee , E.SALARY AS Salary
FROM EMPLOYEE E
LEFT JOIN DEPARTMENT D ON E.DEPARTMENTID = D.ID
RIGHT JOIN (
    SELECT DEPARTMENTID , MAX(SALARY) AS MAX_SAL
    FROM EMPLOYEE
    GROUP BY DEPARTMENTID
) T ON T.DEPARTMENTID = E.DEPARTMENTID AND T.MAX_SAL = E.SALARY