WITH CTE AS(
    SELECT T.* , U.*
    FROM TRIPS T
    LEFT JOIN USERS U ON T.CLIENT_ID = U.USERS_ID
    LEFT JOIN USERS U2 ON T.DRIVER_ID = U2.USERS_ID
    WHERE U.BANNED = 'No' AND
          T.REQUEST_AT BETWEEN '2013-10-01' AND '2013-10-03' AND 
          U2.BANNED = 'No')

SELECT REQUEST_AT AS Day,
ROUND(SUM(IF(STATUS = 'COMPLETED' , 0 , 1)) / COUNT(STATUS) , 2) AS 'Cancellation Rate'
FROM CTE
GROUP BY REQUEST_AT
ORDER BY DAY