SELECT A.PLAYER_ID , A.DEVICE_ID
FROM ACTIVITY A
RIGHT JOIN (
    SELECT  PLAYER_ID , 
            MIN(EVENT_DATE) MIN_DATE
    FROM ACTIVITY
    GROUP BY PLAYER_ID ) T
ON A.PLAYER_ID = T.PLAYER_ID AND A.EVENT_DATE = T.MIN_DATE