SELECT ID , COMPANY , SALARY  FROM
(SELECT ID,
    COMPANY,
    SALARY,
    ROW_NUMBER() OVER (PARTITION BY COMPANY ORDER BY SALARY) AS ROW_CT,
    COUNT(ID) OVER (PARTITION BY COMPANY) AS ID_CT
FROM EMPLOYEE) T
WHERE ROW_CT = ROUND((T.ID_CT + 1) / 2) OR ROW_CT = FLOOR((T.ID_CT + 1) / 2)