WITH CTE AS (
    SELECT 
        CANDIDATEID ,
        COUNT(ID) OVER (PARTITION BY CANDIDATEID) AS MAX_VOTE
    FROM VOTE)

SELECT NAME 
FROM CANDIDATE
WHERE ID IN (
    SELECT DISTINCT CANDIDATEID
    FROM CTE
    WHERE MAX_VOTE = (SELECT MAX(MAX_VOTE) FROM CTE))