WITH CTE AS(
  SELECT S2.ID,
  COUNT(*) OVER (PARTITION BY S1.ID) AS ROW_C
  FROM STADIUM S1
  LEFT JOIN STADIUM S2 ON S2.ID - S1.ID BETWEEN 0 AND 2  
  WHERE S2.PEOPLE >= 100)

SELECT DISTINCT CTE.ID , S.VISIT_DATE , S.PEOPLE 
FROM CTE
LEFT JOIN STADIUM S ON CTE.ID = S.ID
WHERE CTE.ROW_C = 3
ORDER BY CTE.ID