SELECT DISTINCT T.ID ,
CASE 
    WHEN P.ID IS NULL THEN 'Root'
    WHEN S.ID IS NULL THEN 'Leaf'
    ELSE 'Inner' END AS type
FROM TREE T
LEFT JOIN TREE P ON T.P_ID = P.ID
LEFT JOIN TREE S ON T.ID = S.P_ID
