WITH C1 AS(
    SELECT PRODUCT_ID , MIN(YEAR) AS MIN_YEAR
    FROM SALES
    GROUP BY PRODUCT_ID)
SELECT C1.PRODUCT_ID , C1.MIN_YEAR AS FIRST_YEAR , S1.QUANTITY AS QUANTITY, S1.PRICE AS PRICE
FROM C1
LEFT JOIN SALES S1 ON C1.PRODUCT_ID = S1.PRODUCT_ID AND C1.MIN_YEAR = S1.YEAR
