SELECT A.ACTIVITY_DATE as day, COUNT(DISTINCT A.USER_ID) AS active_users
FROM ACTIVITY A
WHERE A.ACTIVITY_DATE BETWEEN DATE_SUB('2019-07-27', INTERVAL 29 DAY) AND '2019-07-27'
GROUP BY A.ACTIVITY_DATE
