WITH CTE AS(
  SELECT DISTINCT C1.VISITED_ON AS DAYS_WANTED
  FROM CUSTOMER C1
  LEFT JOIN CUSTOMER C2 ON DATEDIFF(C1.VISITED_ON , C2.VISITED_ON) >= 6
  WHERE C2.VISITED_ON IS NOT NULL)

SELECT DAYS_WANTED AS visited_on, SUM(C1.AMOUNT) AS amount , ROUND(SUM(AMOUNT) / 7 , 2) AS average_amount
  FROM CTE
  LEFT JOIN CUSTOMER C1 ON DATEDIFF(DAYS_WANTED , C1.VISITED_ON) BETWEEN 0 AND 6
  GROUP BY DAYS_WANTED