WITH CTE AS( 
    SELECT MOVIE_ID , AVG(RATING) AS AVG_RATING
    FROM MOVIERATING
    WHERE CREATED_AT BETWEEN '2020-02-01' AND '2020-02-28'
    GROUP BY MOVIE_ID),
    CTE2 AS(
    SELECT U.NAME AS results
    FROM MOVIERATING M
    LEFT JOIN USERS U ON U.USER_ID = M.USER_ID
    GROUP BY U.USER_ID
    ORDER BY COUNT(rating) DESC , U.NAME 
    LIMIT 1),
    CTE3 AS(
    SELECT M.TITLE
    FROM CTE
    LEFT JOIN MOVIES M ON M.MOVIE_ID = CTE.MOVIE_ID
    ORDER BY AVG_RATING DESC, M.TITLE
    LIMIT 1)

SELECT * FROM CTE2
UNION ALL
SELECT * FROM CTE3